# Configurações do Banco PostgreSQL (Oficial)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gestao_acoes}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
app.required.db-password=${DB_PASSWORD:}
app.required.brapi-token=${BRAPI_TOKEN:}
app.required.twelvedata-api-key=${TWELVEDATA_API_KEY:}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Atualiza as tabelas sem apagar os dados (ideal para dev)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
