# Configurações do Banco PostgreSQL (Oficial)
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_acoes
spring.datasource.username=postgres
spring.datasource.password=sua_senha_aqui

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Atualiza as tabelas sem apagar os dados (ideal para dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true