# Define qual ambiente o Spring vai rodar agora (test ou dev)
spring.profiles.active=test

# Nossas Chaves de API Externas globais
api.brapi.token=rLFSeWPu1T9XtEV4E2XbX3
api.twelvedata.key=bf4fe2d0ddb84d02a30e8ce871bac170