package com.trabalho.gestao_acoes.services;

import com.trabalho.gestao_acoes.domains.*;
import com.trabalho.gestao_acoes.domains.dtos.OperationRequestDTO;
import com.trabalho.gestao_acoes.domains.enums.*;
import com.trabalho.gestao_acoes.repositories.*;
import com.trabalho.gestao_acoes.services.exceptions.*;
import java.math.BigDecimal;
import java.time.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.transaction.annotation.Transactional;
import static org.assertj.core.api.Assertions.*;

@SpringBootTest
@Transactional
class OperationLedgerServiceTest {
 @Autowired OperationLedgerService ledger; @Autowired UserAccountRepository users; @Autowired PortfolioRepository portfolios; @Autowired AcaoRepository acoes; @Autowired CorretoraRepository corretoras; @Autowired PosicaoCarteiraRepository positions; @Autowired TransacaoRepository transactions;
 UserAccount user; Portfolio portfolio; Acao asset; Corretora broker; LocalDateTime date=LocalDateTime.of(2026,1,2,10,0);
 @BeforeEach void setup(){ user=users.save(new UserAccount("ledger"+System.nanoTime(),"ledger"+System.nanoTime()+"@t.test","x",Instant.now())); portfolio=portfolios.save(new Portfolio("Principal",user,Instant.now())); SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(user.getEmail(),"x",java.util.List.of())); asset=asset("PETR4","BRL"); broker=broker("1"); }
 @AfterEach void clear(){SecurityContextHolder.clearContext();}
 @Test void firstPurchaseIncludesCostsAndHasZeroRealized(){ ledger.create(req(TipoTransacao.COMPRA,asset,broker,10,"10", "1","2","0","0","a")); PosicaoCarteira p=pos(asset,broker); assertThat(p.getQuantidadeTotal()).isEqualTo(10); assertThat(p.getPrecoMedio()).isEqualByComparingTo("10.30000000"); assertThat(p.getResultadoRealizado()).isEqualByComparingTo("0"); }
 @Test void successivePurchasesAndPartialSaleKeepAverageAndDeductCosts(){ ledger.create(req(TipoTransacao.COMPRA,asset,broker,10,"10","1","0","0","0","a")); ledger.create(req(TipoTransacao.COMPRA,asset,broker,10,"20","0","2","0","0","b")); ledger.create(req(TipoTransacao.VENDA,asset,broker,5,"20","1","0","0","0","c")); PosicaoCarteira p=pos(asset,broker); assertThat(p.getQuantidadeTotal()).isEqualTo(15); assertThat(p.getPrecoMedio()).isEqualByComparingTo("15.15000000"); assertThat(transactions.findAllByPortfolioId(portfolio.getId()).get(2).getResultadoRealizado()).isEqualByComparingTo("23.25000000"); }
 @Test void totalSaleRemovesPositionAndRebuyStartsNewAverage(){ ledger.create(req(TipoTransacao.COMPRA,asset,broker,2,"10","0","0","0","0","a")); ledger.create(req(TipoTransacao.VENDA,asset,broker,2,"15","0","0","0","0","b")); assertThat(positions.findByAcaoIdAndCorretoraIdAndPortfolioId(asset.getId(),broker.getId(),portfolio.getId())).isEmpty(); assertThat(transactions.findAllByPortfolioId(portfolio.getId()).get(1).getResultadoRealizado()).isEqualByComparingTo("10"); ledger.create(req(TipoTransacao.COMPRA,asset,broker,1,"30","0","0","0","0","c")); assertThat(pos(asset,broker).getPrecoMedio()).isEqualByComparingTo("30"); }
 @Test void rejectsInsufficientAndIdempotencyConflictWithoutPartialWrite(){ OperationRequestDTO first=req(TipoTransacao.COMPRA,asset,broker,1,"10","0","0","0","0","key"); var created=ledger.create(first); assertThatThrownBy(()->ledger.create(req(TipoTransacao.VENDA,asset,broker,2,"10","0","0","0","0","sale"))).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("INSUFFICIENT_POSITION"); assertThat(ledger.create(first).id()).isEqualTo(created.id()); assertThatThrownBy(()->ledger.create(req(TipoTransacao.COMPRA,asset,broker,1,"11","0","0","0","0","key"))).isInstanceOf(ConflictException.class).extracting("code").isEqualTo("IDEMPOTENCY_CONFLICT"); assertThat(transactions.findAllByPortfolioId(portfolio.getId())).hasSize(1); }
 @Test void isolatesBrokersAndRejectsCurrencyMismatch(){ Corretora second=broker("2"); ledger.create(req(TipoTransacao.COMPRA,asset,broker,2,"10","0","0","0","0","a")); ledger.create(req(TipoTransacao.COMPRA,asset,second,3,"20","0","0","0","0","b")); assertThat(pos(asset,broker).getQuantidadeTotal()).isEqualTo(2);assertThat(pos(asset,second).getQuantidadeTotal()).isEqualTo(3); assertThatThrownBy(()->ledger.create(req(TipoTransacao.COMPRA,asset,broker,1,"10","0","0","0","0","usd","USD"))).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("CURRENCY_MISMATCH"); }
 @Test void retroactivePurchaseReplaysLaterSalesAndRejectsInvalidFutureBalance(){ ledger.create(at(TipoTransacao.COMPRA,10,"10",date.plusDays(2),"a")); ledger.create(at(TipoTransacao.VENDA,5,"20",date.plusDays(3),"b")); ledger.create(at(TipoTransacao.COMPRA,10,"20",date.plusDays(1),"c")); assertThat(pos(asset,broker).getQuantidadeTotal()).isEqualTo(15); assertThat(pos(asset,broker).getPrecoMedio()).isEqualByComparingTo("15.00000000"); assertThatThrownBy(()->ledger.create(at(TipoTransacao.VENDA,20,"10",date.minusDays(1),"bad"))).isInstanceOf(BusinessException.class).extracting("code").isEqualTo("INSUFFICIENT_POSITION"); assertThat(transactions.findAllByPortfolioId(portfolio.getId())).hasSize(3); }
 @Test void sameTimestampUsesPersistedIdAndEditAndDeleteReplay(){ var buy=ledger.create(at(TipoTransacao.COMPRA,10,"10",date,"a")); var sale=ledger.create(at(TipoTransacao.VENDA,5,"20",date,"b")); assertThat(transactions.findAllByPortfolioId(portfolio.getId())).extracting(Transacao::getId).containsExactly(buy.id(),sale.id()); ledger.update(buy.id(),at(TipoTransacao.COMPRA,10,"12",date,"a")); assertThat(pos(asset,broker).getPrecoMedio()).isEqualByComparingTo("12"); assertThat(transactions.findByIdAndPortfolioId(sale.id(),portfolio.getId()).orElseThrow().getResultadoRealizado()).isEqualByComparingTo("40"); ledger.delete(sale.id()); assertThat(pos(asset,broker).getQuantidadeTotal()).isEqualTo(10); }
 @Test void invalidEditAndDeleteKeepLedgerUnchanged(){ var buy=ledger.create(at(TipoTransacao.COMPRA,10,"10",date,"a")); var sale=ledger.create(at(TipoTransacao.VENDA,5,"20",date.plusMinutes(1),"b")); assertThatThrownBy(()->ledger.update(buy.id(),at(TipoTransacao.COMPRA,2,"10",date,"a"))).isInstanceOf(BusinessException.class); assertThat(transactions.findByIdAndPortfolioId(buy.id(),portfolio.getId()).orElseThrow().getQuantidade()).isEqualTo(10); assertThatThrownBy(()->ledger.delete(buy.id())).isInstanceOf(BusinessException.class); assertThat(transactions.findByIdAndPortfolioId(buy.id(),portfolio.getId())).isPresent(); assertThat(pos(asset,broker).getQuantidadeTotal()).isEqualTo(5); }
 @Test void fractionalValuesUseMoneyPolicyScaleAndEveryIdempotencyFieldConflicts(){ var base=at(TipoTransacao.COMPRA,3,"10.123456789",date,"key"); var created=ledger.create(base); assertThat(pos(asset,broker).getPrecoMedio()).isEqualByComparingTo("10.12345679"); for(OperationRequestDTO changed: java.util.List.of(at(TipoTransacao.COMPRA,4,"10.123456789",date,"key"),at(TipoTransacao.COMPRA,3,"10.123456789",date.plusMinutes(1),"key"),req(TipoTransacao.COMPRA,asset,broker,3,"10.123456789","1","0","0","0","key"),req(TipoTransacao.COMPRA,asset,broker,3,"10.123456789","0","1","0","0","key"),req(TipoTransacao.COMPRA,asset,broker,3,"10.123456789","0","0","1","0","key"),req(TipoTransacao.COMPRA,asset,broker,3,"10.123456789","0","0","0","1","key"))){assertThatThrownBy(()->ledger.create(changed)).isInstanceOf(ConflictException.class).extracting("code").isEqualTo("IDEMPOTENCY_CONFLICT");} assertThat(created.id()).isNotNull(); }
 @Test void normalizesNotesAndConflictsForPriceAssetAndBroker(){ var base=new OperationRequestDTO(TipoTransacao.COMPRA,asset.getId(),broker.getId(),date,1,"BRL",new BigDecimal("10"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO," nota ","key"); var saved=ledger.create(base); assertThat(ledger.create(new OperationRequestDTO(TipoTransacao.COMPRA,asset.getId(),broker.getId(),date,1,"BRL",new BigDecimal("10"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,"nota","key")).id()).isEqualTo(saved.id()); Corretora other=broker("3"); Acao otherAsset=asset("VALE3","BRL"); for(OperationRequestDTO changed:java.util.List.of(new OperationRequestDTO(TipoTransacao.COMPRA,asset.getId(),broker.getId(),date,1,"BRL",new BigDecimal("11"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,"nota","key"),new OperationRequestDTO(TipoTransacao.COMPRA,otherAsset.getId(),broker.getId(),date,1,"BRL",new BigDecimal("10"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,"nota","key"),new OperationRequestDTO(TipoTransacao.COMPRA,asset.getId(),other.getId(),date,1,"BRL",new BigDecimal("10"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,"nota","key"))){assertThatThrownBy(()->ledger.create(changed)).isInstanceOf(ConflictException.class);} }
 @Test void persistsCanonicalObservationAndUsesItForIdempotency(){
   for(String observation:java.util.Arrays.asList(null,"","   ")) {
     var operation=ledger.create(new OperationRequestDTO(TipoTransacao.COMPRA,asset.getId(),broker.getId(),date.plusMinutes(transactions.count()),1,"BRL",new BigDecimal("10"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,observation,"blank-"+transactions.count()));
     assertThat(transactions.findByIdAndPortfolioId(operation.id(),portfolio.getId()).orElseThrow().getObservacao()).isNull();
   }
   var trimmed=ledger.create(new OperationRequestDTO(TipoTransacao.COMPRA,asset.getId(),broker.getId(),date.plusMinutes(10),1,"BRL",new BigDecimal("10"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,"  conteúdo interno  ","trimmed"));
   assertThat(transactions.findByIdAndPortfolioId(trimmed.id(),portfolio.getId()).orElseThrow().getObservacao()).isEqualTo("conteúdo interno");
   assertThat(ledger.create(new OperationRequestDTO(TipoTransacao.COMPRA,asset.getId(),broker.getId(),date.plusMinutes(10),1,"BRL",new BigDecimal("10"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,"conteúdo interno","trimmed")).id()).isEqualTo(trimmed.id());
   assertThatThrownBy(()->ledger.create(new OperationRequestDTO(TipoTransacao.COMPRA,asset.getId(),broker.getId(),date.plusMinutes(10),1,"BRL",new BigDecimal("10"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,"conteúdo diferente","trimmed"))).isInstanceOf(ConflictException.class).extracting("code").isEqualTo("IDEMPOTENCY_CONFLICT");
   ledger.update(trimmed.id(),new OperationRequestDTO(TipoTransacao.COMPRA,asset.getId(),broker.getId(),date.plusMinutes(10),1,"BRL",new BigDecimal("10"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,"  atualizado  ",null));
   assertThat(transactions.findByIdAndPortfolioId(trimmed.id(),portfolio.getId()).orElseThrow().getObservacao()).isEqualTo("atualizado");
 }
 @Test void isolatesUsersAndDeniesCrossOwnerMutation(){ var op=ledger.create(at(TipoTransacao.COMPRA,2,"10",date,"a")); BigDecimal pm=pos(asset,broker).getPrecoMedio(); UserAccount second=users.save(new UserAccount("second"+System.nanoTime(),"second"+System.nanoTime()+"@t.test","x",Instant.now())); portfolios.save(new Portfolio("Principal",second,Instant.now())); Acao foreignAsset=new Acao();foreignAsset.setOwner(second);foreignAsset.setTicker("ABCD");foreignAsset.setMercado("BRASIL");foreignAsset.setMoeda("BRL");foreignAsset.setCotacaoAtual(BigDecimal.ONE);foreignAsset.setDataHoraCotacao(LocalDateTime.now());acoes.save(foreignAsset); Corretora foreignBroker=new Corretora();foreignBroker.setOwner(second);foreignBroker.setCnpj("99999999999999");foreignBroker.setRazaoSocial("Foreign");foreignBroker.setCep("01001000");foreignBroker.setRegulatoryStatus(RegulatoryStatus.VERIFIED);corretoras.save(foreignBroker); SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(second.getEmail(),"x",java.util.List.of())); assertThatThrownBy(()->ledger.previewUpdate(op.id(),at(TipoTransacao.COMPRA,2,"10",date,"a"))).isInstanceOf(NotFoundException.class); assertThatThrownBy(()->ledger.update(op.id(),at(TipoTransacao.COMPRA,2,"10",date,"a"))).isInstanceOf(NotFoundException.class); assertThatThrownBy(()->ledger.delete(op.id())).isInstanceOf(NotFoundException.class); SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(user.getEmail(),"x",java.util.List.of())); assertThat(transactions.findByIdAndPortfolioId(op.id(),portfolio.getId())).isPresent();assertThat(pos(asset,broker).getPrecoMedio()).isEqualByComparingTo(pm); }
 PosicaoCarteira pos(Acao a,Corretora b){return positions.findByAcaoIdAndCorretoraIdAndPortfolioId(a.getId(),b.getId(),portfolio.getId()).orElseThrow();}
 OperationRequestDTO req(TipoTransacao t,Acao a,Corretora b,int q,String price,String c,String f,String i,String o,String key){return req(t,a,b,q,price,c,f,i,o,key,"BRL");}
 OperationRequestDTO req(TipoTransacao t,Acao a,Corretora b,int q,String price,String c,String f,String i,String o,String key,String currency){return new OperationRequestDTO(t,a.getId(),b.getId(),date.plusMinutes(transactions.count()),q,currency,new BigDecimal(price),new BigDecimal(c),new BigDecimal(f),new BigDecimal(i),new BigDecimal(o),"note",key);}
 OperationRequestDTO at(TipoTransacao t,int q,String price,LocalDateTime when,String key){return new OperationRequestDTO(t,asset.getId(),broker.getId(),when,q,"BRL",new BigDecimal(price),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,"note",key);}
 Acao asset(String ticker,String currency){Acao a=new Acao();a.setOwner(user);a.setTicker(ticker);a.setMercado("BRASIL");a.setMoeda(currency);a.setCotacaoAtual(new BigDecimal("10"));a.setDataHoraCotacao(LocalDateTime.now());return acoes.save(a);}
 Corretora broker(String suffix){Corretora b=new Corretora();b.setOwner(user);b.setCnpj("00000000000"+suffix);b.setRazaoSocial("Broker"+suffix);b.setCep("01001000");b.setRegulatoryStatus(RegulatoryStatus.VERIFIED);return corretoras.save(b);}
}
