package com.trabalho.gestao_acoes.resources;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.trabalho.gestao_acoes.domains.dtos.*;
import com.trabalho.gestao_acoes.services.OperationLedgerService;
import com.trabalho.gestao_acoes.services.exceptions.*;
import com.trabalho.gestao_acoes.resources.exceptions.ResourceExceptionHandler;
import java.math.BigDecimal; import java.time.LocalDateTime;
import org.junit.jupiter.api.*; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc; import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
class OperacaoResourceContractTest {
 MockMvc mvc; OperationLedgerService service; String body="{\"tipo\":\"COMPRA\",\"ativoId\":1,\"corretoraId\":2,\"dataHora\":\"2026-01-02T10:00:00\",\"quantidade\":2,\"moeda\":\"BRL\",\"precoUnitario\":10,\"corretagem\":1,\"taxas\":2,\"impostos\":3,\"outrosCustos\":4,\"observacao\":\"nota\"}";
 @BeforeEach void setup(){service=mock(OperationLedgerService.class);mvc=MockMvcBuilders.standaloneSetup(new OperacaoResource(service)).setControllerAdvice(new ResourceExceptionHandler()).build();}
 @Test void createsAndSerializesLedgerFields() throws Exception {when(service.create(any())).thenReturn(op());mvc.perform(post("/operacoes").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated()).andExpect(jsonPath("$.moeda").value("BRL")).andExpect(jsonPath("$.corretagem").value(1)).andExpect(jsonPath("$.valorBruto").value(20)).andExpect(jsonPath("$.valorTotal").value(30)).andExpect(jsonPath("$.resultadoRealizado").value(0));}
 @Test void previewAndEditPreviewSerializeProjectedPosition() throws Exception {var p=new OperationPreviewDTO(2,new BigDecimal("9"),new BigDecimal("18"),new BigDecimal("20"),new BigDecimal("10"),new BigDecimal("30"),4,new BigDecimal("12"),new BigDecimal("48"),BigDecimal.ZERO,"BRL");when(service.preview(any())).thenReturn(p);when(service.previewUpdate(eq(8L),any())).thenReturn(p);mvc.perform(post("/operacoes/previa").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andExpect(jsonPath("$.quantidadeAnterior").value(2)).andExpect(jsonPath("$.precoMedioProjetado").value(12));mvc.perform(post("/operacoes/8/previa").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk());}
 @Test void updateDeleteListAndErrorsUseHttpContract() throws Exception {when(service.update(eq(8L),any())).thenReturn(op());doNothing().when(service).delete(8L);doThrow(new BusinessException("INSUFFICIENT_POSITION","x")).when(service).create(any());mvc.perform(put("/operacoes/8").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk());mvc.perform(delete("/operacoes/8")).andExpect(status().isNoContent());mvc.perform(get("/operacoes?tipo=COMPRA&ticker=PETR4&corretoraId=2&de=2026-01-01T00:00:00&ate=2026-01-03T00:00:00")).andExpect(status().isOk());mvc.perform(post("/operacoes").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isUnprocessableEntity()).andExpect(jsonPath("$.code").value("INSUFFICIENT_POSITION"));}
 OperationDTO op(){return new OperationDTO(8L,"COMPRA",1L,"PETR4",2L,"B",2,"BRL",new BigDecimal("10"),BigDecimal.ONE,new BigDecimal("2"),new BigDecimal("3"),new BigDecimal("4"),new BigDecimal("20"),new BigDecimal("30"),BigDecimal.ZERO,LocalDateTime.of(2026,1,2,10,0),"nota");}
}
